import { Question } from './types';

export const quizQuestions: Question[] = [
  // Biology
  {
    id: 1,
    questionText: "Which of the following describes the application of scientific methods in biological experiments?",
    options: ["Only data collection", "Only testing of hypothesis", "Testing of hypothesis, data collection, and analysis", "Observing nature without analysis"],
    correctAnswerIndex: 2,
  },
  {
    id: 2,
    questionText: "Which of these is NOT one of the four main types of biological molecules discussed in the course content?",
    options: ["Carbohydrate", "Lipids", "Amino acids (as a main type, not a building block of protein)", "Nucleic acids"],
    correctAnswerIndex: 2,
  },
  {
    id: 3,
    questionText: "Which of the following is a key difference between plant and animal cells?",
    options: ["Animal cells have a cell wall, plant cells do not.", "Both plant and animal cells typically have chloroplasts.", "Plant cells have a cell wall and chloroplasts, which animal cells lack.", "Animal cells are generally larger than plant cells."],
    correctAnswerIndex: 2,
  },
  {
    id: 4,
    questionText: "Mendel’s Laws of Inheritance can be practically verified using which method mentioned in the course content?",
    options: ["Microscopic observation of cell division", "Biochemical analysis of DNA", "Determination of inheritance using coloured seeds (e.g., beads, grains)", "Studying human genetic disorders like sickle cell anemia"],
    correctAnswerIndex: 2,
  },
  {
    id: 5,
    questionText: "Which of the following is a basic concept in ecology mentioned in the course content?",
    options: ["Hybridization", "Food web", "Osmosis", "Mitosis"],
    correctAnswerIndex: 1,
  },
  {
    id: 6,
    questionText: "The period between 1860-1910 is known as the golden era of microbiology. Which significant theory emerged during this time?",
    options: ["The theory of evolution", "The germ theory of disease", "The theory of spontaneous generation", "The theory of relativity"],
    correctAnswerIndex: 1,
  },
  {
    id: 7,
    questionText: "Which of the following structures is found in bacterial cells?",
    options: ["Nucleus", "Mitochondria", "Flagella", "Chloroplasts"],
    correctAnswerIndex: 2,
  },
  {
    id: 8,
    questionText: "What is a key difference between prokaryotic and eukaryotic cells?",
    options: ["Eukaryotic cells are generally smaller than prokaryotic cells.", "Prokaryotic cells lack a true nucleus and membrane-bound organelles, unlike eukaryotic cells.", "Only prokaryotic cells have cell walls.", "Eukaryotic cells do not contain genetic material."],
    correctAnswerIndex: 1,
  },
  {
    id: 9,
    questionText: "Which process is involved in the transfer of genetic materials in prokaryotes?",
    options: ["Meiosis", "Mitosis", "Conjugation (implied by \"transfer of genetic materials in prokaryotes\" given the context of microbial genetics)", "Sexual reproduction"],
    correctAnswerIndex: 2,
  },
  {
    id: 10,
    questionText: "In which field can microorganisms be biotechnologically applied according to the course content?",
    options: ["Astronomy", "Meteorology", "Food industry", "Geology"],
    correctAnswerIndex: 2,
  },
  {
    id: 11,
    questionText: "Which of the following is a group of lower plants mentioned in the course content?",
    options: ["Angiosperms", "Gymnosperms", "Bryophytes", "Spermatophytes"],
    correctAnswerIndex: 2,
  },
  {
    id: 12,
    questionText: "In-situ conservation of plants involves which approach?",
    options: ["Maintaining plant genetic resources in botanical gardens.", "Storing plant seeds in seed banks.", "Protecting plant species within their natural habitats.", "Propagating plants in controlled laboratory conditions."],
    correctAnswerIndex: 2,
  },
  {
    id: 13,
    questionText: "Which plant tissue is primarily responsible for the transport of water and minerals from the roots to the rest of the plant?",
    options: ["Phloem", "Epidermis", "Parenchyma", "Xylem"],
    correctAnswerIndex: 3,
  },
  {
    id: 14,
    questionText: "Plants that obtain their nutrition through chemosynthesis are classified as:",
    options: ["Heterotrophic", "Holozoic", "Saprophytic", "Autotrophic"],
    correctAnswerIndex: 3,
  },
  {
    id: 15,
    questionText: "What are Chordates known for, regarding their interaction with different habitats?",
    options: ["Exclusively living in aquatic environments.", "Lacking any form of adaptation to land.", "Exhibiting challenges and adaptations to living in water, land, and air.", "Being confined to a single habitat type."],
    correctAnswerIndex: 2,
  },
  {
    id: 16,
    questionText: "Which of the following is a component of the human circulatory/transport system?",
    options: ["Lymphatic fluid", "Bile", "Urine", "Blood"],
    correctAnswerIndex: 3,
  },
  {
    id: 17,
    questionText: "The course content for General Biology begins by defining the science of biology. What does it state is included in this initial topic?",
    options: ["Only the origin of organic molecules.", "Only the brief history of the first cells.", "Definition of biology and its branches.", "Only basic biostatistics."],
    correctAnswerIndex: 2,
  },
  // Chemistry
  {
    id: 18,
    questionText: "How is mass spectrometry used in chemistry according to the course content?",
    options: ["To determine the boiling point of compounds.", "To measure the pH of solutions.", "In the determination of Relative Atomic Mass and calculation of relative abundances and isotopic masses.", "To identify types of chemical reactions."],
    correctAnswerIndex: 2,
  },
  {
    id: 19,
    questionText: "What is the primary difference between empirical and molecular formulae?",
    options: ["Empirical formula shows the exact number of atoms, while molecular formula shows the simplest ratio.", "Empirical formula shows the simplest whole-number ratio of atoms, while molecular formula shows the actual number of atoms.", "Empirical formula is calculated from combustion data, molecular formula is not.", "Molecular formula is only applicable to ionic compounds."],
    correctAnswerIndex: 1,
  },
  {
    id: 20,
    questionText: "Bohr's theory primarily explains which phenomenon?",
    options: ["The wave-particle duality of matter.", "The photoelectric effect.", "The atomic spectra of hydrogen.", "The continuous spectrum of blackbody radiation."],
    correctAnswerIndex: 2,
  },
  {
    id: 21,
    questionText: "Which principle states that electrons will occupy degenerate orbitals singly before pairing up?",
    options: ["Aufbau principle", "Pauli’s exclusion principle", "Hund’s rule", "Bohr's assumption"],
    correctAnswerIndex: 2,
  },
  {
    id: 22,
    questionText: "Which type of bonding involves the complete transfer of electrons between atoms?",
    options: ["Ionic bonding", "Covalent bonding", "Metallic bonding", "Coordinate covalent bonding"],
    correctAnswerIndex: 0,
  },
  {
    id: 23,
    questionText: "The valence shell electron-pair repulsion theory (VSEPR) is used to predict:",
    options: ["The reactivity of molecules.", "The bond energy of molecules.", "The shapes of simple molecules like H2O and NH3.", "The electrical conductivity of compounds."],
    correctAnswerIndex: 2,
  },
  {
    id: 24,
    questionText: "Which of the following is an assumption of the kinetic theory of gases?",
    options: ["Gas particles experience significant attractive forces.", "Gas particles occupy a significant volume compared to the container.", "Gas particles are in constant, random motion.", "Collisions between gas particles are inelastic."],
    correctAnswerIndex: 2,
  },
  {
    id: 25,
    questionText: "Which of the following is an example of a colligative property?",
    options: ["Density", "Viscosity", "Elevation of boiling point", "Surface tension"],
    correctAnswerIndex: 2,
  },
  {
    id: 26,
    questionText: "Hess's Law is used in thermochemistry for:",
    options: ["Determining reaction rates.", "Calculating activation energy.", "Constructing energy cycles and calculating enthalpy changes.", "Explaining the deviation of real gases."],
    correctAnswerIndex: 2,
  },
  {
    id: 27,
    questionText: "According to the course content, Faraday’s first and second laws of electrolysis are associated with which industrial application?",
    options: ["Ammonia production (Haber process).", "Sulfuric acid production (Contact process).", "Extraction of metals from their ores.", "Petroleum refining."],
    correctAnswerIndex: 2,
  },
  {
    id: 28,
    questionText: "In chemical kinetics, what is defined as the number of reacting species (atoms, ions, or molecules) that are involved in a single step of a reaction?",
    options: ["Reaction order", "Rate of reaction", "Molecularity", "Rate determining step"],
    correctAnswerIndex: 2,
  },
  {
    id: 29,
    questionText: "According to Le-Chatelier’s principle, what happens to a system at equilibrium if the temperature is increased for an exothermic reaction?",
    options: ["The equilibrium shifts to the product side.", "The equilibrium remains unchanged.", "The equilibrium shifts to the reactant side.", "The rate of both forward and reverse reactions increases equally."],
    correctAnswerIndex: 2,
  },
  {
    id: 30,
    questionText: "What is a general trend in the physical and chemical properties of Period III elements and their compounds (chlorides, oxides, and hydrides)?",
    options: ["Increasing metallic character across the period.", "Gradation from metallic to non-metallic properties.", "Decreasing electronegativity across the period.", "Consistent reactivity with water for all elements."],
    correctAnswerIndex: 1,
  },
  {
    id: 31,
    questionText: "Which of the following is an allotropic form of carbon discussed in the course content?",
    options: ["Quartz", "Asbestos", "Fullerene", "Silicon carbide"],
    correctAnswerIndex: 2,
  },
  {
    id: 32,
    questionText: "What is a key characteristic of transition elements?",
    options: ["They exclusively form +1 oxidation states.", "They are typically unreactive metals.", "They tend to form variable oxidation states.", "They primarily form covalent bonds."],
    correctAnswerIndex: 2,
  },
  {
    id: 33,
    questionText: "What is the definition of homolytic fission of a covalent bond?",
    options: ["One atom receives both electrons from the bond.", "Each atom receives one electron from the shared pair.", "The bond breaks due to the action of a nucleophile.", "The bond breaks after reaction with an electrophile."],
    correctAnswerIndex: 1,
  },
  {
    id: 34,
    questionText: "Which type of isomerism includes Cis/Trans and E/Z notations?",
    options: ["Position isomerism", "Functional group isomerism", "Geometrical isomerism", "Optical isomerism"],
    correctAnswerIndex: 2,
  },
  // Physics
  {
    id: 35,
    questionText: "Which of the following is an importance of dimensional analysis?",
    options: ["To determine the actual value of a physical quantity.", "To calculate the error in a measurement.", "To check the consistency of an equation.", "To convert scalar quantities to vector quantities."],
    correctAnswerIndex: 2,
  },
  {
    id: 36,
    questionText: "According to Newton’s Laws of Motion, what is a condition for equilibrium of forces acting at a point?",
    options: ["The net force is constant and non-zero.", "The object is accelerating.", "The vector sum of all forces acting on the object is zero.", "Forces are only acting in one dimension."],
    correctAnswerIndex: 2,
  },
  {
    id: 37,
    questionText: "How does centripetal acceleration differ from centrifugal acceleration?",
    options: ["Centripetal acceleration is an apparent force, while centrifugal is real.", "Centripetal acceleration acts outwards, while centrifugal acts inwards.", "Centripetal acceleration is directed towards the center of rotation, while centrifugal is an apparent force directed away from the center.", "Centripetal acceleration only applies to linear motion."],
    correctAnswerIndex: 2,
  },
  {
    id: 38,
    questionText: "Which concept describes the behavior of a material that can be drawn into a wire without breaking?",
    options: ["Brittleness", "Elastic limit", "Ductility", "Plastic deformation"],
    correctAnswerIndex: 2,
  },
  {
    id: 39,
    questionText: "What is a key difference between heat and temperature?",
    options: ["Heat is a measure of the average kinetic energy of particles, while temperature is the total internal energy.", "Heat is the transfer of thermal energy, while temperature is a measure of the average kinetic energy of particles.", "Heat is an intensive property, while temperature is an extensive property.", "They are interchangeable terms in physics."],
    correctAnswerIndex: 1,
  },
  {
    id: 40,
    questionText: "In the context of Stefan-Boltzmann’s law, what is a blackbody?",
    options: ["An object that reflects all incident radiation.", "An object that only emits radiation at very low temperatures.", "An ideal object that absorbs all incident electromagnetic radiation and emits thermal radiation characteristic of its temperature.", "An object that primarily emits visible light."],
    correctAnswerIndex: 2,
  },
  {
    id: 41,
    questionText: "Which of the following is a wave characteristic?",
    options: ["Reflection", "Diffraction", "Interference", "Wavelength"],
    correctAnswerIndex: 3,
  },
  {
    id: 42,
    questionText: "What phenomenon occurs when light travels from a denser medium to a less dense medium at an angle greater than the critical angle?",
    options: ["Refraction", "Diffraction", "Total internal reflection", "Dispersion"],
    correctAnswerIndex: 2,
  },
  {
    id: 43,
    questionText: "Coulomb’s Law describes the force between:",
    options: ["Magnetic poles.", "Gravitational masses.", "Electric charges.", "Moving conductors."],
    correctAnswerIndex: 2,
  },
  {
    id: 44,
    questionText: "How is the total capacitance calculated for capacitors connected in parallel?",
    options: ["The reciprocal of the sum of the reciprocals of individual capacitances.", "The product of the individual capacitances.", "The average of the individual capacitances.", "The sum of the individual capacitances."],
    correctAnswerIndex: 3,
  },
  {
    id: 45,
    questionText: "Which law is associated with the conservation of charge and energy in electrical circuits?",
    options: ["Ohm’s Law", "Faraday's Law", "Kirchoff’s Laws", "Lenz Law"],
    correctAnswerIndex: 2,
  },
  {
    id: 46,
    questionText: "Lenz's Law describes the direction of:",
    options: ["Electric current in a resistive circuit.", "Force on a current-carrying conductor.", "Induced electromotive force (EMF) in a circuit.", "Magnetic field around a straight wire."],
    correctAnswerIndex: 2,
  },
  {
    id: 47,
    questionText: "The Hydrogen Spectrum is characterized by:",
    options: ["A continuous range of colours.", "Absorption lines in the ultraviolet region.", "Discrete spectral lines corresponding to specific energy transitions.", "A broad band of emitted radiation."],
    correctAnswerIndex: 2,
  },
  {
    id: 48,
    questionText: "The phenomenon where electrons are emitted from a heated metal surface is called:",
    options: ["Photoelectric emission", "Compton effect", "Thermionic emission", "Electron diffraction"],
    correctAnswerIndex: 2,
  },
  {
    id: 49,
    questionText: "Bragg’s Law is fundamentally important for understanding which phenomenon?",
    options: ["The photoelectric effect.", "The emission of light from atomic spectra.", "Crystal diffraction of X-rays.", "The wave nature of particles."],
    correctAnswerIndex: 2,
  },
  {
    id: 50,
    questionText: "What concept is explained by the de Broglie formula and the Compton Effect?",
    options: ["The quantization of energy.", "The uncertainty principle.", "The wave-particle duality of light/matter.", "The stability of atomic nuclei."],
    correctAnswerIndex: 2,
  },
];
