import { Question } from './types';

export const quizQuestions: Question[] = [
  // Accounting
  {
    id: 1,
    questionText: "Which of the following is a general objective for candidates writing the Accounting paper?",
    options: ["Design marketing strategies for multinational corporations.", "Reconcile Cash Book balance with the Bank Statement balance.", "Develop new economic theories for market analysis.", "Formulate government tax policies for developing countries."],
    correctAnswerIndex: 1,
  },
  {
    id: 2,
    questionText: "According to ACC 001: Basic Financial Accounting, which of these is a fundamental accounting concept?",
    options: ["Marketing mix", "Human resource management", "Going concern", "Supply chain management"],
    correctAnswerIndex: 2,
  },
  {
    id: 3,
    questionText: "The basic accounting equation is stated as:",
    options: ["Revenue = Expenses + Profit", "Assets = Capital + Liabilities", "Income = Savings + Investment", "Debit = Credit + Balance"],
    correctAnswerIndex: 1,
  },
  {
    id: 4,
    questionText: "Which body is responsible for the development of International Financial Reporting Standards (IFRS)?",
    options: ["World Bank", "International Monetary Fund (IMF)", "International Accounting Standards Board (IASB)", "Federal Inland Revenue Service (FIRS)"],
    correctAnswerIndex: 2,
  },
  {
    id: 5,
    questionText: "IAS 16 primarily deals with the accounting for:",
    options: ["Inventories", "Presentation of Financial Statements", "Property, Plant and Equipment", "Cash Flow Statements"],
    correctAnswerIndex: 2,
  },
  {
    id: 6,
    questionText: "Which of the following is considered a source document in bookkeeping?",
    options: ["Trial balance", "Ledger", "Invoice", "Income statement"],
    correctAnswerIndex: 2,
  },
  {
    id: 7,
    questionText: "The principle of double entry dictates that every transaction has:",
    options: ["One debit and one credit entry of different amounts", "Multiple debit entries and a single credit entry", "Equal debit and credit entries", "No direct impact on ledger accounts"],
    correctAnswerIndex: 2,
  },
  {
    id: 8,
    questionText: "An error where a transaction is completely omitted from the books of account is an example of an error:",
    options: ["Affecting the trial balance", "Not affecting the trial balance", "Of transposition", "Of casting"],
    correctAnswerIndex: 1,
  },
  {
    id: 9,
    questionText: "Which accounting concept explains the linkage among going concern, periodicity, and matching in the preparation of financial statements?",
    options: ["Objectivity concept", "Prudence concept", "Realisation concept", "Periodicity concept"],
    correctAnswerIndex: 3,
  },
  {
    id: 10,
    questionText: "In manufacturing accounts, what is the sum of direct materials, direct labour, and direct expenses referred to as?",
    options: ["Factory overheads", "Cost of goods manufactured", "Prime cost", "Work-in-progress"],
    correctAnswerIndex: 2,
  },
  {
    id: 11,
    questionText: "One of the specific objectives of ACC 002: Basic Cost and Management Accounting is to:",
    options: ["Prepare financial statements for sole proprietorships", "Compute taxes payable by applying corporate tax rates", "Analyse and predict cost behaviour as output and markets vary", "Discuss the nature and structure of Nigerian tax administration"],
    correctAnswerIndex: 2,
  },
  {
    id: 12,
    questionText: "Which of the following is a classification of cost according to its behaviour?",
    options: ["Material cost", "Direct cost", "Fixed cost", "Production cost"],
    correctAnswerIndex: 2,
  },
  {
    id: 13,
    questionText: "The Economic Order Quantity (EOQ) is a model used in the control of:",
    options: ["Labour costs", "Overhead costs", "Inventory", "Administrative expenses"],
    correctAnswerIndex: 2,
  },
  {
    id: 14,
    questionText: "In the context of auditing, the concept of 'true and fair view' is primarily associated with:",
    options: ["Audit communication", "Audit report", "Legal framework for auditing", "Auditing guidelines"],
    correctAnswerIndex: 1,
  },
  // Business Studies
  {
    id: 15,
    questionText: "Which of the following is a general objective for candidates undertaking Business Studies courses?",
    options: ["Reconcile Cash Book balance with Bank Statement balance", "Discuss issues relating to budgeting, financial management and financial performance", "Prepare the Financial Statements of Not-for-Profit Organisations", "Explain the concepts and principles of auditing"],
    correctAnswerIndex: 1,
  },
  {
    id: 16,
    questionText: "The 'triple bottom line' for social enterprises includes which three targets?",
    options: ["Marketing, sales, and profit", "Economic (financial), social, and environmental", "Production, distribution, and consumption", "Capital, labour, and management"],
    correctAnswerIndex: 1,
  },
  {
    id: 17,
    questionText: "Which of the following is considered a primary economic sector business?",
    options: ["Manufacturing plant", "Retail store", "Fishing industry", "Consultancy firm"],
    correctAnswerIndex: 2,
  },
  {
    id: 18,
    questionText: "A change from a sole proprietorship to a partnership is an example of a problem resulting from:",
    options: ["Diversification", "Internationalization", "Changing from one legal structure to another", "Market penetration"],
    correctAnswerIndex: 2,
  },
  {
    id: 19,
    questionText: "Which of these is explicitly listed as a stakeholder in a business?",
    options: ["Researchers", "Government", "Financial analysts", "Competitors"],
    correctAnswerIndex: 1,
  },
  {
    id: 20,
    questionText: "Meaning, reasons for delegation, why managers refuse delegation, and why subordinates resist delegation are all topics covered under which organisational concept?",
    options: ["Centralization", "Decentralization", "Delegation of Authority", "Organisational Structures"],
    correctAnswerIndex: 2,
  },
  {
    id: 21,
    questionText: "Which school of management thought is mentioned in BUS 002 Management 1?",
    options: ["Post-modern management", "Quantum management", "Behavioural management", "Evolutionary management"],
    correctAnswerIndex: 2,
  },
  {
    id: 22,
    questionText: "Maslow, Herzberg, and McClelland are theorists associated with which management topic?",
    options: ["Leadership styles", "Motivation", "Human resource management", "Marketing concepts"],
    correctAnswerIndex: 1,
  },
  {
    id: 23,
    questionText: "Job description and specifications are elements typically found within the scope of:",
    options: ["Marketing research", "Labour costing", "Human Resource Management (HRM)", "Strategic management"],
    correctAnswerIndex: 2,
  },
  {
    id: 24,
    questionText: "In the context of marketing, what are primary and secondary research examples of?",
    options: ["Marketing mix elements", "Market segmentation strategies", "Market research types", "Channels of distribution"],
    correctAnswerIndex: 2,
  },
  {
    id: 25,
    questionText: "One of the specific objectives for BUS 003 Finance and Accounting is to:",
    options: ["Explain the concept of true and fair view in auditing", "Apply accounting information to decision making", "Discuss the nature and structure of Nigerian tax administration", "Analyse and predict cost behaviour"],
    correctAnswerIndex: 1,
  },
  {
    id: 26,
    questionText: "Which of the following is a short-term source of finance mentioned in the course content?",
    options: ["Debentures", "Overdrafts", "Issue of shares", "Retained earnings"],
    correctAnswerIndex: 1,
  },
  {
    id: 27,
    questionText: "SWOT analysis is a tool primarily used in:",
    options: ["Operational planning", "Inventory management", "Strategic analysis", "Business communication"],
    correctAnswerIndex: 2,
  },
  // Economics
  {
    id: 28,
    questionText: "One of the general objectives of the Economics course study is to:",
    options: ["Prepare financial statements for limited liability companies", "Reconcile Cash Book balance with the Bank Statement balance", "Develop the ability to apply analytical tools, knowledge and skills to solve societies' economic problems", "Demonstrate understanding of concepts and principles of auditing"],
    correctAnswerIndex: 2,
  },
  {
    id: 29,
    questionText: "Which of the following economists is mentioned in the \"Definition of Economics\" sub-topic?",
    options: ["John Maynard Keynes", "Adam Smith", "Milton Friedman", "Paul Samuelson"],
    correctAnswerIndex: 1,
  },
  {
    id: 30,
    questionText: "The basic economic problem of scarcity is linked to which fundamental questions?",
    options: ["What, when, and why to produce", "What, how, where, and for whom to produce", "Who, what, and how much to consume", "How, where, and by whom to distribute"],
    correctAnswerIndex: 1,
  },
  {
    id: 31,
    questionText: "The Production Possibility Curve illustrates which basic economic concept?",
    options: ["Market equilibrium", "Opportunity cost", "Consumer utility", "National income"],
    correctAnswerIndex: 1,
  },
  {
    id: 32,
    questionText: "Factors influencing demand, such as price, income, and cross elasticity, are discussed under which main topic?",
    options: ["Theory of the Firm", "Theory of Consumer Behaviour", "The Price System", "Government Intervention"],
    correctAnswerIndex: 2,
  },
  {
    id: 33,
    questionText: "The Law of Diminishing Marginal Utility is a concept found within the:",
    options: ["Theory of the Firm", "Theory of Consumer Behaviour", "Market Structure", "Economic Systems"],
    correctAnswerIndex: 1,
  },
  {
    id: 34,
    questionText: "In the context of the Theory of the Firm, land, labour, capital, and entrepreneur are examples of:",
    options: ["Fixed costs", "Factors of production", "Variable outputs", "Market structures"],
    correctAnswerIndex: 1,
  },
  {
    id: 35,
    questionText: "Which of the following is NOT listed as a different market structure?",
    options: ["Perfect Competition", "Oligopoly", "Communism", "Monopoly"],
    correctAnswerIndex: 2,
  },
  {
    id: 36,
    questionText: "Market imperfections, monopolistic elements, and externalities are identified as sources of:",
    options: ["Economic efficiency", "Market failure", "Government revenue", "Consumer surplus"],
    correctAnswerIndex: 1,
  },
  {
    id: 37,
    questionText: "Gross National Product (GNP) and Gross Domestic Product (GDP) are concepts related to:",
    options: ["Circular Flow of Income", "National Income Accounting", "Theory of National Income Determination", "Public Finance"],
    correctAnswerIndex: 1,
  },
  {
    id: 38,
    questionText: "The Keynesian Theory primarily focuses on:",
    options: ["The quantity theory of money", "Aggregate Demand and Aggregate Supply", "Classical economic growth", "Efficient resource allocation"],
    correctAnswerIndex: 1,
  },
  {
    id: 39,
    questionText: "The principles of Absolute and Comparative Advantage are theories associated with:",
    options: ["Population growth", "International Trade", "Economic Development", "Macro-economic Objectives"],
    correctAnswerIndex: 1,
  },
  {
    id: 40,
    questionText: "Which of the following is listed as a major international economic institution?",
    options: ["Federal Inland Revenue Service (FIRS)", "Economic Community of West African States (ECOWAS)", "Central Bank of Nigeria", "State Board of Internal Revenue (SBIR)"],
    correctAnswerIndex: 1,
  },
];
